style: formatting

diff --git a/xdotool/functions b/xdotool/functions
--- a/xdotool/functions
+++ b/xdotool/functions
@@ -4,110 +4,110 @@
 # stored in zstyle) is active, and exits with 1 if not; it does support TMUX,
 # but doesn't support tabs.
 is-terminal-active() {
-    local plugin_dir
+	local plugin_dir
 
-    zstyle -s ':notify:' plugin-dir plugin_dir
-    source "$plugin_dir"/lib
+	zstyle -s ':notify:' plugin-dir plugin_dir
+	source "$plugin_dir"/lib
 
-    function is-terminal-window-active {
-        local active_wid wid
+	function is-terminal-window-active {
+		local active_wid wid
 
-        active_wid=$(xdotool getwindowfocus)
+		active_wid=$(xdotool getwindowfocus)
 
-        zstyle -s ':notify:' window-id wid
+		zstyle -s ':notify:' window-id wid
 
-        if [[ "$active_wid" == "$wid" ]]; then
-            return 0
-        fi
+		if [[ "$active_wid" == "$wid" ]]; then
+			return 0
+		fi
 
-        return 1
-    }
+		return 1
+	}
 
-    if is-terminal-window-active; then
-        if is-inside-tmux; then
-            is-current-tmux-pane-active
-            return $?
-        fi
-    else
-        return $?
-    fi
+	if is-terminal-window-active; then
+		if is-inside-tmux; then
+			is-current-tmux-pane-active
+			return $?
+		fi
+	else
+		return $?
+	fi
 }
 
 function zsh-notify() {
-    local message type time_elapsed title icon body
+	local message type time_elapsed title icon body
 
-    if ! command -v notify-send > /dev/null 2>&1; then
-        echo cannot find notify-send in \$PATH 1>&2
-        return 1
-    fi
+	if ! command -v notify-send > /dev/null 2>&1; then
+		echo cannot find notify-send in \$PATH 1>&2
+		return 1
+	fi
 
-    if [[ $# -lt 2 ]]; then
-        echo usage: notifier TYPE TIME_ELAPSED 1>&2
-        return 1
-    fi
+	if [[ $# -lt 2 ]]; then
+		echo usage: notifier TYPE TIME_ELAPSED 1>&2
+		return 1
+	fi
 
-    zstyle -s ':notify:' plugin-dir plugin_dir
-    source "$plugin_dir"/lib
+	zstyle -s ':notify:' plugin-dir plugin_dir
+	source "$plugin_dir"/lib
 
-    type="$1"
-    time_elapsed="$(format-time "$2")"
-    exit_code="$3"
-    command=$(<&0)
+	type="$1"
+	time_elapsed="$(format-time "$2")"
+	exit_code="$3"
+	command=$(<&0)
 
-    zstyle -s ':notify:' "$type"-sound notification_sound
-    zstyle -s ':notify:' "$type"-icon icon
-    zstyle -s ':notify:' app-name app_name
-    zstyle -s ':notify:' expire-time expire_time
+	zstyle -s ':notify:' "$type"-sound notification_sound
+	zstyle -s ':notify:' "$type"-icon icon
+	zstyle -s ':notify:' app-name app_name
+	zstyle -s ':notify:' expire-time expire_time
 
-    zstyle -s ':notify:' "$type"-title title
-    zstyle -s ':notify:' message-body body
+	zstyle -s ':notify:' "$type"-title title
+	zstyle -s ':notify:' message-body body
 
-    title=$(notification-format "$title" time_elapsed "$time_elapsed" exit-code "$exit_code")
-    message=$(notification-format "$body" command "$command")
+	title=$(notification-format "$title" time_elapsed "$time_elapsed" exit-code "$exit_code")
+	message=$(notification-format "$body" command "$command")
 
-    if [[ -n "$icon" ]]; then
-        icon_option="-i $icon"
-    fi
+	if [[ -n "$icon" ]]; then
+		icon_option="-i $icon"
+	fi
 
-    if [[ -z "$app_name" ]]; then
-            app_name="${message%% *}"
-            message="${message#* }"
-    fi
+	if [[ -z "$app_name" ]]; then
+			app_name="${message%% *}"
+			message="${message#* }"
+	fi
 
-    notify-send -a "${=app_name}" -t $expire_time ${=icon_option} "$title" -- "$message"
+	notify-send -a "${=app_name}" -t $expire_time ${=icon_option} "$title" -- "$message"
 
-    function play-sound {
-        if command -v paplay > /dev/null 2>&1; then
-            paplay "$1" &> /dev/null &
-        elif command -v aplay > /dev/null 2>&1; then
-            aplay "$1" &> /dev/null &
-        elif command -v ossplay > /dev/null 2>&1; then
-            ossplay "$1" &> /dev/null &
-        else
-            echo "could not find a sound file player." >&2
-            return 1
-        fi
-    }
+	function play-sound {
+		if command -v paplay > /dev/null 2>&1; then
+			paplay "$1" &> /dev/null &
+		elif command -v aplay > /dev/null 2>&1; then
+			aplay "$1" &> /dev/null &
+		elif command -v ossplay > /dev/null 2>&1; then
+			ossplay "$1" &> /dev/null &
+		else
+			echo "could not find a sound file player." >&2
+			return 1
+		fi
+	}
 
-    if [[ -n "$notification_sound" ]]; then
-        if [[ -a "$notification_sound" ]]; then
-            play-sound "$notification_sound"
-        else
-            echo "file $notification_sound not found." >&2
-        fi
-    fi
+	if [[ -n "$notification_sound" ]]; then
+		if [[ -a "$notification_sound" ]]; then
+			play-sound "$notification_sound"
+		else
+			echo "file $notification_sound not found." >&2
+		fi
+	fi
 
-    if command -v wmctrl > /dev/null 2>&1; then
-        local wid
+	if command -v wmctrl > /dev/null 2>&1; then
+		local wid
 
-        zstyle -s ':notify:' window-id wid
+		zstyle -s ':notify:' window-id wid
 
-        if zstyle -t ':notify:' activate-terminal; then
-            wmctrl -ia $wid
-        elif ! (zstyle -t ':notify:' disable-urgent); then
-            wmctrl -i -r $wid -b add,demands_attention
-        fi
-    fi
+		if zstyle -t ':notify:' activate-terminal; then
+			wmctrl -ia $wid
+		elif ! (zstyle -t ':notify:' disable-urgent); then
+			wmctrl -i -r $wid -b add,demands_attention
+		fi
+	fi
 }
 
 # NOTE: Using the initial `WINDOWID` value can result in false negatives with
@@ -126,24 +126,24 @@ function zsh-notify() {
 # existing shells in the previous window, but in all other cases it will be
 # incorrect.
 function store-window-id() {
-    if ! (zstyle -t ':notify:' check-focus); then
-        return
-    fi
+	if ! (zstyle -t ':notify:' check-focus); then
+		return
+	fi
 
-    local always_check
-    zstyle -b ':notify:' always-check-active-window always_check || true
+	local always_check
+	zstyle -b ':notify:' always-check-active-window always_check || true
 
-    # some linux terminals such as gnome-terminal don't set the WINDOWID, so we
-    # check if it's empty. If it's empty or the user explicitly requests it (see
-    # the function documentation for details on why this is needed), we capture
-    # the ID of the window that is _now_ focused. This should be the window of
-    # the terminal used to type the command, as this function is run as a prexec
-    # hook.
-    if [[ -z "$WINDOWID" || "$always_check" == 'yes' ]]; then
-        zstyle ':notify:*' window-id "$(xdotool getwindowfocus)"
-    else
-        zstyle ':notify:*' window-id "$WINDOWID"
-    fi
+	# some linux terminals such as gnome-terminal don't set the WINDOWID, so we
+	# check if it's empty. If it's empty or the user explicitly requests it (see
+	# the function documentation for details on why this is needed), we capture
+	# the ID of the window that is _now_ focused. This should be the window of
+	# the terminal used to type the command, as this function is run as a prexec
+	# hook.
+	if [[ -z "$WINDOWID" || "$always_check" == 'yes' ]]; then
+		zstyle ':notify:*' window-id "$(xdotool getwindowfocus)"
+	else
+		zstyle ':notify:*' window-id "$WINDOWID"
+	fi
 }
 
 autoload -U add-zsh-hook
